Update readme
SAP/cgo-ase pull request #14
Opened 2021-01-14 12:47 UTC by ntnn

**Description**

Update readme.

**Related issues**

Link any related issues here.

**Tests**

- [ ] make integration

2021-01-14 15:01 UTC, fwilhelm92 commented on README.md
> +Aside from the shard object the cgo driver has no special requirements
`shard` = `shared`?

2021-01-14 15:01 UTC, fwilhelm92 commented on README.md
> +other than Go standard library and the third part modules listed in
```suggestion
other than Go standard library and the third party modules listed in
```

2021-01-15 07:51 UTC, cb80 requested changes

2021-01-15 07:51 UTC, cb80 commented on README.md
> +`go.mod`, e.g.  `github.com/SAP/go-dblib`.
```suggestion
`go.mod`, e.g. `github.com/SAP/go-dblib`.
```

2021-01-18 07:27 UTC, fwilhelm92 approved these changes

2021-01-18 14:58 UTC, cb80 approved these changes

2021-01-18 15:28 UTC, merged